ALTER SERVER ROLE [sysadmin] ADD MEMBER [DESKTOP-I19NO7E\ktsmi];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [NT SERVICE\SQLWriter];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [NT SERVICE\Winmgmt];

